### ISSUE TITLE
TypeError - Cannot read property 'skin' of undefined

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-render#123]
### Error

```
Uncaught TypeError: Cannot read property 'skin' of undefined
    at RenderWebGL._touchingBounds (gui.js:78346)
    at RenderWebGL.isTouchingDrawables (gui.js:78111)
    at RenderedTarget.module.exports.RenderedTarget.isTouchingSprite (gui.js:6476)
    at Scratch3SensingBlocks.module.exports.Scratch3SensingBlocks.touchingObject (gui.js:14503)
    at execute (gui.js:15231)
    at Sequencer.module.exports.Sequencer.stepThread (gui.js:16309)
    at Sequencer.module.exports.Sequencer.stepThreads (gui.js:16267)
    at Runtime.module.exports.Runtime._step (gui.js:15939)
    at Runtime.<anonymous> (gui.js:16190)
```

### Steps to Reproduce

https://llk.github.io/scratch-gui/#138787028

### Operating System and Browser

Mac OS 10.12.3 Chrome Version 56.0.2924.87 (64-bit)

**Comment by paulkaplan** [comment]
FWIW I found another example of this while playing this ninja game :) Right at the panel with the shurikens it starts happening.

https://llk.github.io/scratch-gui/#154866875/

**Comment by paulkaplan** [comment]
I'm having trouble creating a minimum replication of this bug. This is the smallest I have so far:

![screen shot 2017-06-06 at 10 23 31 am](https://cloud.githubusercontent.com/assets/654102/26834414/4a67663e-4aa3-11e7-87fa-37bea3f3c7e3.png)

**Comment by jwzimmer** [comment]
This came up again (reported by Kim) during the Google Serve meeting (6/5/17).

### Expected Behavior

The bird should walk across the screen, and you should use space to move through the dialogue. (As in 2.0.)

### Actual Behavior

> video intro freezes shortly after it starts

This error is in the console:
```
scratch-render.js:9714 Uncaught TypeError: Cannot read property 'skin' of undefined
    at RenderWebGL.getSkinSize (scratch-render.js:9714)
    at RenderedTarget.setSize (scratch-vm.js:2619)
    at Scratch3LooksBlocks.changeSize (scratch-vm.js:15903)
    at execute (scratch-vm.js:17894)
    at Sequencer.stepThread (scratch-vm.js:19343)
    at Sequencer.stepThreads (scratch-vm.js:19298)
    at Runtime._step (scratch-vm.js:18683)
    at scratch-vm.js:19064
```

### Steps to Reproduce

> Start the program.  Press play.  On 2.0, there's an animated intro and then you see text.  On 3.0, the animated intro starts and then freezes.

Compare 159330855 in 2.0 vs. 3.0.

### Operating System and Browser

Kim: _Firefox 53.0.3 (32-bit), Windows 10_
@jwzimmer (repro): _Mac OS, Chrome Version 58.0.3029.110 (64-bit)_

<img width="1280" alt="screen shot 2017-06-06 at 12 44 44 pm" src="https://user-images.githubusercontent.com/1320456/26841024-3fc33466-4ab6-11e7-8024-833d05f371ec.png">

**Comment by paulkaplan** [comment]
Fixed by https://github.com/LLK/scratch-vm/pull/598

**Comment by thisandagain** [comment]
I'm still seeing this but possibly in a new way. Repro steps:

- Load https://llk.github.io/scratch-gui/develop/player.html#173499153
- Press "s" to start the game
- Press "down arrow" to stop an alien! 👽 💥 
- `Uncaught TypeError: Cannot read property 'skin' of undefined`

**Comment by paulkaplan** [comment]
@thisandagain cannot repro, despite playing that game for farrrrr too long :) Can you confirm that you can still do it?

**Comment by thisandagain** [comment]
![image](https://user-images.githubusercontent.com/747641/34268718-cae0693a-e64f-11e7-9a62-d96da476422e.png)

Nope! Can't repro.
